version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=cent_beauty
      - MYSQL_USER=anhvt3010
      - MYSQL_PASSWORD=@fIP1pQWIiB-Jol6U^W)

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cent_beauty
      MYSQL_USER: anhvt3010
      MYSQL_PASSWORD: '@fIP1pQWIiB-Jol6U^W)'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: